### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by awwsmm** [awwsmm/awwsmm.com#7]
See: https://barhamon.com/feed.json

**Comment by awwsmm** [comment]
Very low priority. Assigning p4.

**Comment by farzadmf** [comment]
I stumbled upon your DEAR article and really liked it; I'm using RSS for all the blogs I follow, so I wish the priority of this one could be bumped up 🙂

**Comment by awwsmm** [comment]
Hey @farzadmf , I think I've done this correctly...

You should now be able to see RSS feeds at

https://www.awwsmm.com/rss.json and
https://www.awwsmm.com/rss.xml

Please let me know if you notice anything broken / weird.

**Comment by awwsmm** [comment]
Followed this guide: https://blog.logrocket.com/adding-rss-feed-next-js-app

Used this library: https://github.com/jpmonette/feed

RSS specification: https://www.rssboard.org/rss-specification

JSON Feed specification: https://www.jsonfeed.org/version/1

Commits
- https://github.com/awwsmm/awwsmm.com/commit/8769407b695c59b988375f14b9a4a5d3cc182c4c
- https://github.com/awwsmm/awwsmm.com/commit/0137cfc7838360a86ef5849dd995c7217b3420d5
- https://github.com/awwsmm/awwsmm.com/commit/0b8d6907bd6534ce63ac348bc5dad9a1f47451f0

**Comment by farzadmf** [comment]
Hey @awwsmm , sorry for the late reply

Thank you for taking care of that. I added to my feed reader, and it seems to be working.

Really liked your DEAR articles BTW; very close to my heart!
